// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PostFornecedorTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void postFornecedor() {
    driver.get("http://127.0.0.1:5500/views/Fornecedor/fornecedorPost.html");
    driver.manage().window().setSize(new Dimension(1440, 774));
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("teste@gmail.com");
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Patrick");
    driver.findElement(By.name("senha")).click();
    driver.findElement(By.name("senha")).sendKeys("12345");
    driver.findElement(By.name("telefone")).click();
    driver.findElement(By.name("telefone")).sendKeys("32991636806");
    driver.findElement(By.name("cnpj")).click();
    driver.findElement(By.name("cnpj")).sendKeys("1231254657676");
    driver.findElement(By.name("dataEntrega")).click();
    driver.findElement(By.name("dataEntrega")).sendKeys("0002-06-15");
    driver.findElement(By.name("dataEntrega")).sendKeys("0020-06-15");
    driver.findElement(By.name("dataEntrega")).sendKeys("0202-06-15");
    driver.findElement(By.name("dataEntrega")).sendKeys("2022-06-15");
    driver.findElement(By.name("empresa")).click();
    driver.findElement(By.name("empresa")).sendKeys("TesteEmpresa");
    driver.findElement(By.name("responsavel")).click();
    driver.findElement(By.cssSelector(".box")).click();
    driver.findElement(By.name("responsavel")).click();
    driver.findElement(By.name("responsavel")).sendKeys("Patrick");
    driver.findElement(By.name("cep")).click();
    driver.findElement(By.name("cep")).sendKeys("36080000");
    driver.findElement(By.name("uf")).sendKeys("MG");
    driver.findElement(By.name("cidade")).sendKeys("Juiz de Fora");
    driver.findElement(By.name("logradouro")).sendKeys("Rua Bernardo Mascarenhas");
    driver.findElement(By.name("bairro")).sendKeys("Fábrica");
    driver.findElement(By.name("numero")).sendKeys("979");
    driver.findElement(By.name("complemento")).click();
    driver.findElement(By.name("complemento")).sendKeys("Apto 102");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector(".box")).click();
    assertThat(driver.findElement(By.cssSelector("p")).getText(), is("FORNECEDOR CADASTRADO!"));
  }
}
