// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PutFornecedorTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void putFornecedor() {
    driver.get("http://127.0.0.1:5500/views/Fornecedor/fornecedorPut.html");
    driver.manage().window().setSize(new Dimension(1440, 774));
    driver.findElement(By.name("id_fornecedor")).click();
    driver.findElement(By.name("id_fornecedor")).sendKeys("1");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("patricknovo@gmail.com");
    driver.findElement(By.name("nome")).sendKeys("Patrick Novo");
    driver.findElement(By.name("senha")).sendKeys("1234567");
    driver.findElement(By.name("telefone")).sendKeys("321243546575");
    driver.findElement(By.name("cnpj")).sendKeys("213125465756786");
    driver.findElement(By.name("dataEntrega")).click();
    driver.findElement(By.name("dataEntrega")).sendKeys("0002-09-18");
    driver.findElement(By.name("dataEntrega")).sendKeys("0020-09-18");
    driver.findElement(By.name("dataEntrega")).sendKeys("0202-09-18");
    driver.findElement(By.name("dataEntrega")).sendKeys("2022-09-18");
    driver.findElement(By.name("empresa")).click();
    driver.findElement(By.name("empresa")).sendKeys("EmpresaNova");
    driver.findElement(By.name("responsavel")).sendKeys("Patrick Novo");
    driver.findElement(By.name("cep")).sendKeys("367687988");
    driver.findElement(By.name("uf")).click();
    driver.findElement(By.name("uf")).sendKeys("MG");
    driver.findElement(By.name("cidade")).click();
    driver.findElement(By.name("cidade")).sendKeys("Juiz de Fora");
    driver.findElement(By.name("logradouro")).click();
    driver.findElement(By.name("logradouro")).sendKeys("Rua Teste do Teste");
    driver.findElement(By.name("bairro")).sendKeys("Teste");
    driver.findElement(By.name("numero")).sendKeys("978");
    driver.findElement(By.name("complemento")).sendKeys("Fundos");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector(".box")).click();
    assertThat(driver.findElement(By.cssSelector("p")).getText(), is("FORNECEDOR ALTERADO!"));
  }
}
